name: app

type: nodejs:10

hooks:
  build: |
    npm install
    npm run build

# There is no need for a writable file mount, so set it to the smallest possible size.
disk: 256

web:
  commands:
    # Run a no-op process that uses no CPU resources, since this is a static site.
    start: sleep infinity
  locations:
    "/":
      root: "dist"
      index:
        - "index.html"
      passthru: /index.html  
      # Set a 5 minute cache lifetime on all static files.
      expires: 300s
      # Disable all scripts, since we don't have any anyway.
      scripts: false
      # By default do not allow any files to be served.
      allow: false
      # Whitelist common image file formats, plus HTML files, robots.txt
      # All other requests will be rejected.
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|pdf|svg?)$:
          allow: true
        ^/robots\.txt$:
          allow: true
